using System.Reflection;

namespace Serpy.Core.Qemu;

/// <summary>
/// The compiled-in descriptor trust anchor — the publisher public key
/// <see cref="DescriptorVerifier"/> trusts to verify the QEMU runtime descriptor
/// (IR3/IKTD3/IR7).
///
/// This value is <b>never a hardcoded literal in source</b>: it is injected at
/// build time via the <c>SerpyDescriptorTrustKey</c> MSBuild property, surfaced
/// as assembly metadata (see <c>Serpy.Core.csproj</c>). A hardcoded test key
/// compiled into every build — including Release — would let any build trust
/// artifacts signed by a known development key, defeating IR7's "no bypass in
/// production" requirement.
///
/// <list type="bullet">
/// <item><b>Release publish builds</b> (<c>-p:SerpyReleasePublish=true</c>, set
/// only by the actual release packaging pipeline — never by the standard
/// <c>dotnet build -c Release</c>/<c>dotnet test -c Release</c> dev/test
/// commands) MUST supply the real Serpy publisher key via
/// <c>-p:SerpyDescriptorTrustKey=&lt;base64 SPKI&gt;</c> (a release CI secret).
/// The build itself fails (<c>RequireReleaseDescriptorTrustKey</c> MSBuild
/// target) if this is not supplied — there is no silent fallback.</item>
/// <item><b>Local dev/test builds</b> (<c>SerpyReleasePublish</c> not set) may
/// auto-pick up the gitignored local test key at
/// <c>.local-signing/descriptor-signing-public.b64</c> (generated by
/// <c>eng/gen-descriptor-signing-key.sh</c>) purely for convenience; this never
/// happens in a release publish build.</item>
/// </list>
/// </summary>
internal static class DescriptorTrustAnchor
{
    /// <summary>
    /// Base64-encoded SubjectPublicKeyInfo (DER) of the trusted key, or
    /// <see langword="null"/> when this build has no trust anchor configured.
    /// </summary>
    public static string? PublicKeySpkiBase64 { get; } = ReadMetadata("SerpyDescriptorTrustKey");

    /// <summary>Human-readable provenance of the configured key ("release-ci", "local-dev-test-key", or null).</summary>
    public static string? Source { get; } = ReadMetadata("SerpyDescriptorTrustKeySource");

    private static string? ReadMetadata(string key)
    {
        var assembly = typeof(DescriptorTrustAnchor).Assembly;
        foreach (var attr in assembly.GetCustomAttributes<AssemblyMetadataAttribute>())
        {
            if (attr.Key != key) continue;
            return string.IsNullOrEmpty(attr.Value) ? null : attr.Value;
        }
        return null;
    }
}
