using System.Reflection;

namespace Serpy.Core.Qemu;

/// <summary>
/// The compiled-in expected Authenticode publisher subject for
/// <c>Serpy.InstallerBootstrapper.exe</c> (IR7) — the identity
/// <see cref="HelperSignatureVerifier"/> must match before
/// <see cref="ManagedRuntimeResolver"/> ever launches it with elevation.
///
/// This value is <b>never a hardcoded literal in source</b>: it is injected at
/// build time via the <c>SerpyHelperPublisherSubject</c> MSBuild property,
/// surfaced as assembly metadata (see <c>Serpy.Core.csproj</c>), mirroring the
/// <see cref="DescriptorTrustAnchor"/> pattern exactly. A hardcoded test
/// publisher subject compiled into every build — including Release — would
/// let a Release build trust a helper signed by a known development
/// certificate, defeating IR7's "no bypass in production" requirement.
///
/// <list type="bullet">
/// <item><b>Release publish builds</b> (<c>-p:SerpyReleasePublish=true</c>, set
/// only by the actual release packaging pipeline) MUST supply the real Serpy
/// publisher subject via <c>-p:SerpyHelperPublisherSubject=&lt;subject&gt;</c>
/// (a release CI value). The build itself fails
/// (<c>RequireReleaseHelperPublisherSubject</c> MSBuild target) if this is
/// not supplied — there is no silent fallback.</item>
/// <item><b>Local dev/test builds</b> (<c>SerpyReleasePublish</c> not set) may
/// auto-pick up the local test-signing certificate's subject
/// (<c>CN=Serpy Test Publisher, O=Serpy Dev, C=US</c>, generated by
/// <c>eng/gen-test-signing-cert.ps1</c>) purely for convenience; this never
/// happens in a release publish build.</item>
/// </list>
/// </summary>
internal static class HelperPublisherAnchor
{
    /// <summary>
    /// Expected Authenticode subject of the elevated bootstrapper, or
    /// <see langword="null"/> when this build has no publisher anchor configured.
    /// </summary>
    public static string? ExpectedSubject { get; } = ReadMetadata("SerpyHelperPublisherSubject");

    /// <summary>Human-readable provenance of the configured subject ("release-ci", "local-dev-test-cert", or null).</summary>
    public static string? Source { get; } = ReadMetadata("SerpyHelperPublisherSubjectSource");

    private static string? ReadMetadata(string key)
    {
        var assembly = typeof(HelperPublisherAnchor).Assembly;
        foreach (var attr in assembly.GetCustomAttributes<AssemblyMetadataAttribute>())
        {
            if (attr.Key != key) continue;
            return string.IsNullOrEmpty(attr.Value) ? null : attr.Value;
        }
        return null;
    }
}
