using System.Security.Cryptography;
using System.Text;
using Serpy.Core.Qemu;

namespace Serpy.Core.Tests.Qemu;

public sealed class DescriptorVerifierTests
{
    private static RuntimeDescriptor MakeDescriptor(string qemuVersion = "11.1.0") => new(
        QemuVersion: qemuVersion,
        InstallerUrl: "https://qemu.weilnetz.de/w64/qemu-w64-setup-20260811.exe",
        InstallerSha256: "f98a8aeb5f7faea9765b6dee28316c266cd179d80354a2fed8e50176f9a2e59f",
        SourceUrl: "https://download.qemu.org/qemu-11.1.0.tar.xz",
        LicenseNoticeUrl: "https://www.qemu.org/");

    // ── Pure sign/verify roundtrip (throwaway keys — fully reproducible anywhere) ──

    [Fact]
    public void TryVerify_ValidSignatureFromMatchingKey_ReturnsTrue()
    {
        using var rsa = RSA.Create(2048);
        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, rsa);
        var signed = new SignedRuntimeDescriptor(descriptor, signature);

        var trustedKey = rsa.ExportSubjectPublicKeyInfo();
        Assert.True(DescriptorVerifier.TryVerify(signed, trustedKey));
    }

    [Fact]
    public void TryVerify_SignatureFromDifferentKey_ReturnsFalse()
    {
        using var signingKey = RSA.Create(2048);
        using var wrongTrustKey = RSA.Create(2048);
        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, signingKey);
        var signed = new SignedRuntimeDescriptor(descriptor, signature);

        Assert.False(DescriptorVerifier.TryVerify(signed, wrongTrustKey.ExportSubjectPublicKeyInfo()));
    }

    [Fact]
    public void TryVerify_TamperedInstallerSha256_ReturnsFalse()
    {
        // The attack this defends against: an attacker who can modify the
        // installer SHA-256 in transit/storage after signing must not be able to
        // redirect trust to a different (malicious) binary.
        using var rsa = RSA.Create(2048);
        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, rsa);

        var tampered = descriptor with { InstallerSha256 = new string('f', 64) };
        var signed = new SignedRuntimeDescriptor(tampered, signature);

        Assert.False(DescriptorVerifier.TryVerify(signed, rsa.ExportSubjectPublicKeyInfo()));
    }

    [Fact]
    public void TryVerify_TamperedInstallerUrl_ReturnsFalse()
    {
        // An attacker redirecting the URL while keeping the original SHA-256 must
        // also fail — the whole descriptor is covered by one signature, not just
        // the hash field.
        using var rsa = RSA.Create(2048);
        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, rsa);

        var tampered = descriptor with { InstallerUrl = "https://attacker.invalid/evil.exe" };
        var signed = new SignedRuntimeDescriptor(tampered, signature);

        Assert.False(DescriptorVerifier.TryVerify(signed, rsa.ExportSubjectPublicKeyInfo()));
    }

    [Fact]
    public void TryVerify_CorruptedSignatureBytes_ReturnsFalseWithoutThrowing()
    {
        using var rsa = RSA.Create(2048);
        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, rsa);
        signature[0] ^= 0xFF; // flip bits — corrupt but same length

        var signed = new SignedRuntimeDescriptor(descriptor, signature);
        Assert.False(DescriptorVerifier.TryVerify(signed, rsa.ExportSubjectPublicKeyInfo()));
    }

    [Fact]
    public void TryVerify_EmptySignature_ReturnsFalseWithoutThrowing()
    {
        using var rsa = RSA.Create(2048);
        var descriptor = MakeDescriptor();
        var signed = new SignedRuntimeDescriptor(descriptor, []);

        Assert.False(DescriptorVerifier.TryVerify(signed, rsa.ExportSubjectPublicKeyInfo()));
    }

    [Fact]
    public void CanonicalBytes_DifferentQemuVersionsProduceDifferentBytes()
    {
        var a = MakeDescriptor("11.1.0");
        var b = MakeDescriptor("11.1.1");
        Assert.NotEqual(
            Encoding.UTF8.GetString(a.CanonicalBytes()),
            Encoding.UTF8.GetString(b.CanonicalBytes()));
    }

    // ── Compiled-in trust anchor (VerifyOrThrow) ──────────────────────────────
    // Uses the real local dev key pair generated by eng/gen-descriptor-signing-key.sh.
    // The private key is deliberately gitignored (never committed, even as a test
    // key), so this test skips gracefully where it is not present — matching the
    // repo's existing environment-gated pattern for hardware/host-dependent tests.

    private static string? FindLocalPrivateKeyPath()
    {
        var dir = AppContext.BaseDirectory;
        for (var i = 0; i < 8 && dir is not null; i++, dir = Path.GetDirectoryName(dir))
        {
            var candidate = Path.Combine(dir, ".local-signing", "descriptor-signing-private.pem");
            if (File.Exists(candidate)) return candidate;
        }
        return null;
    }

    [Fact]
    public void VerifyOrThrow_RealLocalDevKeyPair_SignatureVerifiesAgainstCompiledInPublicKey()
    {
        var privateKeyPath = FindLocalPrivateKeyPath();
        if (privateKeyPath is null)
            return; // no local dev signing key present in this environment — skip

        using var rsa = RSA.Create();
        rsa.ImportFromPem(File.ReadAllText(privateKeyPath));

        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, rsa);
        var signed = new SignedRuntimeDescriptor(descriptor, signature);

        // If this fails, the compiled-in TestPublicKeySpkiBase64 constant does not
        // match .local-signing/descriptor-signing-public.pem -- the pair drifted.
        var verified = DescriptorVerifier.VerifyOrThrow(signed);
        Assert.Equal(descriptor, verified);
    }

    [Fact]
    public void VerifyOrThrow_WrongKeySignature_ThrowsInvalidOperationException()
    {
        using var rsa = RSA.Create(2048); // definitely not the trusted key
        var descriptor = MakeDescriptor();
        var signature = DescriptorSigner.Sign(descriptor, rsa);
        var signed = new SignedRuntimeDescriptor(descriptor, signature);

        var ex = Assert.Throws<InvalidOperationException>(() => DescriptorVerifier.VerifyOrThrow(signed));
        Assert.Contains("signature verification failed", ex.Message, StringComparison.OrdinalIgnoreCase);
    }
}
