using System.Diagnostics;
using System.Runtime.Versioning;
using System.Security.Cryptography.X509Certificates;
using Serpy.Core.Qemu;

namespace Serpy.Windows.IntegrationTests;

/// <summary>
/// Real accept-path proof for <see cref="HelperSignatureVerifier"/> (IR7): a
/// properly Authenticode-signed, chain-trusted binary must verify as valid via
/// the actual <c>WinVerifyTrust</c> call this repo ships, not merely via an
/// external tool.
///
/// Opt-in: requires the local dev test signing cert generated by
/// <c>eng/gen-test-signing-cert.ps1</c> at <c>.local-signing/serpy-test-signing.pfx</c>
/// (gitignored, never committed) and mutates the CurrentUser certificate trust
/// stores for the duration of one test, always cleaned up in <c>finally</c> by
/// exact thumbprint. Skips gracefully — does not fail — when the local test cert
/// is not present, matching the repo's existing hardware/host-dependent test
/// pattern (e.g. <c>QemuSmokeTests</c>' <c>SERPY_RUN_SMOKE</c> gate).
/// </summary>
[SupportedOSPlatform("windows")]
public sealed class HelperSignatureVerifierAcceptTests
{
    private const string TestPfxPassword = "serpy-test-only";
    private const string TestSubject = "CN=Serpy Test Publisher, O=Serpy Dev, C=US";

    private static string? FindLocalSigningDir()
    {
        var dir = AppContext.BaseDirectory;
        for (var i = 0; i < 8 && dir is not null; i++, dir = Path.GetDirectoryName(dir))
        {
            var candidate = Path.Combine(dir, ".local-signing");
            if (Directory.Exists(candidate) &&
                File.Exists(Path.Combine(candidate, "serpy-test-signing.pfx")))
                return candidate;
        }
        return null;
    }

    [Fact]
    public void Verify_TrustedSignedBinary_ReturnsValidWithMatchingSubject()
    {
        var signingDir = FindLocalSigningDir();
        if (signingDir is null) return; // no local dev test cert present -- skip

        var pfxPath = Path.Combine(signingDir, "serpy-test-signing.pfx");
        var cerPath = Path.Combine(signingDir, "serpy-test-signing.cer");
        using var cert = X509CertificateLoader.LoadPkcs12FromFile(pfxPath, TestPfxPassword, X509KeyStorageFlags.Exportable);

        var rootImported = false;
        var publisherImported = false;
        string? signedExe = null;

        try
        {
            using (var rootStore = new X509Store(StoreName.Root, StoreLocation.CurrentUser))
            {
                rootStore.Open(OpenFlags.ReadWrite);
                using var publicOnly = X509CertificateLoader.LoadCertificateFromFile(cerPath);
                rootStore.Add(publicOnly);
                rootImported = true;
            }
            using (var pubStore = new X509Store(StoreName.TrustedPublisher, StoreLocation.CurrentUser))
            {
                pubStore.Open(OpenFlags.ReadWrite);
                using var publicOnly = X509CertificateLoader.LoadCertificateFromFile(cerPath);
                pubStore.Add(publicOnly);
                publisherImported = true;
            }

            // Sign via the OS's own Set-AuthenticodeSignature -- fixture creation only;
            // the assertion below exercises OUR HelperSignatureVerifier.Verify(), not this.
            var sourceExe = typeof(HelperSignatureVerifierAcceptTests).Assembly.Location;
            signedExe = Path.Combine(Path.GetTempPath(), $"serpy-sig-accept-{Guid.NewGuid():N}.dll");
            File.Copy(sourceExe, signedExe);

            RunPowerShellSign(signedExe, pfxPath, TestPfxPassword);

            var result = HelperSignatureVerifier.Verify(signedExe, TestSubject);

            Assert.True(result.ChainIsTrusted, $"Expected trusted chain; got: {result.Message}");
            Assert.True(result.SubjectMatches, $"Expected subject match; got: {result.ActualSubject}");
            Assert.True(result.IsValid);

            // Wrong expected subject must still be rejected even though the chain trusts.
            var wrongExpected = HelperSignatureVerifier.Verify(signedExe, "CN=Someone Else, O=Not Serpy, C=US");
            Assert.False(wrongExpected.SubjectMatches);
            Assert.False(wrongExpected.IsValid);
        }
        finally
        {
            if (signedExe is not null && File.Exists(signedExe)) File.Delete(signedExe);

            if (rootImported)
            {
                using var rootStore = new X509Store(StoreName.Root, StoreLocation.CurrentUser);
                rootStore.Open(OpenFlags.ReadWrite);
                var toRemove = rootStore.Certificates.Find(X509FindType.FindByThumbprint, cert.Thumbprint, false);
                foreach (var c in toRemove.Cast<X509Certificate2>()) rootStore.Remove(c);
            }
            if (publisherImported)
            {
                using var pubStore = new X509Store(StoreName.TrustedPublisher, StoreLocation.CurrentUser);
                pubStore.Open(OpenFlags.ReadWrite);
                var toRemove = pubStore.Certificates.Find(X509FindType.FindByThumbprint, cert.Thumbprint, false);
                foreach (var c in toRemove.Cast<X509Certificate2>()) pubStore.Remove(c);
            }
        }
    }

    private static void RunPowerShellSign(string filePath, string pfxPath, string password)
    {
        var script =
            $"$c = New-Object System.Security.Cryptography.X509Certificates.X509Certificate2(" +
            $"'{pfxPath}', (ConvertTo-SecureString -String '{password}' -Force -AsPlainText), 'Exportable'); " +
            $"$r = Set-AuthenticodeSignature -FilePath '{filePath}' -Certificate $c -HashAlgorithm SHA256; " +
            $"if ($r.Status -ne 'Valid') {{ throw \"sign failed: $($r.Status) $($r.StatusMessage)\" }}";

        var psi = new ProcessStartInfo("powershell.exe")
        {
            UseShellExecute = false,
            CreateNoWindow = true,
            RedirectStandardError = true,
            RedirectStandardOutput = true,
        };
        psi.ArgumentList.Add("-NoProfile");
        psi.ArgumentList.Add("-ExecutionPolicy");
        psi.ArgumentList.Add("Bypass");
        psi.ArgumentList.Add("-Command");
        psi.ArgumentList.Add(script);

        using var proc = Process.Start(psi) ?? throw new InvalidOperationException("Could not start powershell.exe.");
        var stderr = proc.StandardError.ReadToEnd();
        proc.WaitForExit();
        if (proc.ExitCode != 0)
            throw new InvalidOperationException($"Signing fixture setup failed: {stderr}");
    }
}
